// Interface text in both languages. Arabic is a first draft: copywriting is reviewed later.
export const SITE = {
  url: 'https://blueyolk.org',
  email: 'hello@blueyolk.org',
  founder: 'Tony Keyrouz',
};

export const LANGS = ['en', 'ar'];

export const T = {
  en: {
    lang: 'en', dir: 'ltr', hreflang: 'en', label: 'EN', switchTo: 'ع', switchLabel: 'العربية',
    siteName: 'Blue Yolk',
    tagline: "A lab for things that don't fit in one category.",
    homeTitle: 'Blue Yolk — production lab and studio',
    homeDesc: 'Blue Yolk is a production lab and studio: film, brand worlds and campaigns, shown as a digital museum.',
    eyebrow: 'Production lab and studio',
    enter: 'Enter the work',
    skip: 'Skip to content',
    menu: 'Menu', close: 'Close', scroll: 'Scroll',
    nav: { work: 'Work', journal: 'Journal', lab: 'Lab', about: 'About', contact: 'Contact' },
    selected: 'Selected exhibits',
    allWork: 'All work',
    fromJournal: 'From the journal',
    allJournal: 'All entries',
    invite: 'Collaborations, co-productions, script consultations.',
    inviteAction: 'Write to us',
    workTitle: 'Work',
    workDesc: 'Exhibits from the Blue Yolk lab: film, brand worlds, campaigns and music.',
    workIntro: 'Exhibits from the lab: film, brand worlds, campaigns and music.',
    filterAll: 'All',
    disciplines: { film: 'Film', brand: 'Brand worlds', campaign: 'Campaigns', music: 'Music video', documentary: 'Documentary', tvc: 'TV commercials', digital: 'Digital', installation: 'Art installations', tv: 'TV shows' },
    year: 'Year', role: 'Role', discipline: 'Discipline', credits: 'Credits',
    next: 'Next exhibit',
    back: 'Back to work',
    journalTitle: 'Journal',
    journalDesc: 'New work, selected projects from here and abroad, milestones and news from Blue Yolk.',
    journalIntro: 'New work, selected projects from here and abroad, milestones and news.',
    categories: { work: 'Work', selection: 'Selection', milestone: 'Milestone', news: 'News' },
    backJournal: 'Back to the journal',
    labTitle: 'Lab',
    labDesc: 'Blue Yolk is meant to become an open-source creative lab. This is the manifesto so far.',
    aboutTitle: 'About',
    aboutDesc: 'Tony Keyrouz, Founder of Blue Yolk: art director, director and film producer working across MENA and Europe.',
    contactTitle: 'Contact',
    contactDesc: 'Write to Blue Yolk about collaborations, co-productions and script consultations.',
    contactLead: 'Write to us.',
    contactBody: 'Open to project collaborations, co-production conversations and script consultations.',
    contactEz: 'Campaigns and brand work',
    standin: 'Stand-in',
    standinNote: 'Stand-in content: replace with real work.',
    notFoundTitle: 'Not found',
    notFoundBody: 'This room does not exist yet.',
    notFoundLink: 'Back to the entrance',
    footerLine: 'A production lab',
    rights: 'All rights reserved.',
    readMore: 'Open',
    landHint: 'Welcome. Press the yolk and move it.',
    landLabel: 'Press the yolk and move it to choose a page',
    museumTitle: 'A museum of things we made.',
    museumCount: (n) => `${n} exhibits · touch the yolk`,
    museumHint: 'drag to move across it · tap a frame to enter',
    viewMap: 'Map', viewIndex: 'Index', zoomIn: 'Zoom in', zoomOut: 'Zoom out',
    open: 'Open', edgeOfMap: 'the edge of the map',
    indexTitle: 'Index', allWorkLabel: 'All work',
    exhibitsN: (n) => (n === 1 ? '1 exhibit' : `${n} exhibits`),
    allYears: 'All years', byYear: 'Year', byCategory: 'Category',
    nothingHere: 'Nothing here yet. Try another year or category.',
    stills: 'Stills', watch: 'Watch film', frame: 'Frame', backProject: 'Back to the project', backIndex: 'Index',
    stillsTitle: (n) => `${n}: stills`, stillsDesc: (n) => `Selected stills from ${n}.`,
    frameOf: (a, b) => `${a} / ${b}`,
    catDesc: (c) => `${c} from the Blue Yolk lab.`,
    labLead: 'Blue is the ink. Yolk is the life. Together they make something new.',
    meetFounder: 'Meet the founder', writeUs: 'Write to us',
    offers: ['Collaborations', 'Co-productions', 'Script consultations'],
    copyMail: 'Copy address', copied: 'Copied',
    readEntry: 'Read',
    startingFilm: 'Starting the film', nowPlaying: 'Now playing',
    minutes: (n) => `${n} min`,
  },
  ar: {
    lang: 'ar', dir: 'rtl', hreflang: 'ar', label: 'ع', switchTo: 'EN', switchLabel: 'English',
    siteName: 'بلو يولك',
    tagline: 'مختبر للأشياء التي لا تتسع لها فئة واحدة.',
    homeTitle: 'بلو يولك — مختبر الإنتاج والاستوديو',
    homeDesc: 'بلو يولك مختبر إنتاج واستوديو: أفلام وعوالم علامات وحملات، تُعرض كمتحف رقمي.',
    eyebrow: 'مختبر الإنتاج والاستوديو',
    enter: 'ادخل إلى الأعمال',
    skip: 'تخطَّ إلى المحتوى',
    menu: 'القائمة', close: 'إغلاق', scroll: 'مرّر',
    nav: { work: 'الأعمال', journal: 'اليوميات', lab: 'المختبر', about: 'من نحن', contact: 'تواصل' },
    selected: 'معروضات مختارة',
    allWork: 'كل الأعمال',
    fromJournal: 'من اليوميات',
    allJournal: 'كل المدخلات',
    invite: 'تعاون، إنتاج مشترك، استشارات نصوص.',
    inviteAction: 'اكتب إلينا',
    workTitle: 'الأعمال',
    workDesc: 'معروضات من مختبر بلو يولك: أفلام وعوالم علامات وحملات وموسيقى.',
    workIntro: 'معروضات من المختبر: أفلام وعوالم علامات وحملات وموسيقى.',
    filterAll: 'الكل',
    disciplines: { film: 'أفلام', brand: 'عوالم العلامات', campaign: 'حملات', music: 'فيديو موسيقي', documentary: 'وثائقي', tvc: 'إعلانات تلفزيونية', digital: 'رقمي', installation: 'أعمال تركيبية', tv: 'برامج تلفزيونية' },
    year: 'السنة', role: 'الدور', discipline: 'المجال', credits: 'الفريق',
    next: 'المعروض التالي',
    back: 'العودة إلى الأعمال',
    journalTitle: 'اليوميات',
    journalDesc: 'أعمال جديدة ومشاريع مختارة من هنا ومن الخارج ومحطات وأخبار من بلو يولك.',
    journalIntro: 'أعمال جديدة ومشاريع مختارة من هنا ومن الخارج ومحطات وأخبار.',
    categories: { work: 'عمل', selection: 'اختيار', milestone: 'محطة', news: 'خبر' },
    backJournal: 'العودة إلى اليوميات',
    labTitle: 'المختبر',
    labDesc: 'يهدف بلو يولك إلى أن يصير مختبرًا إبداعيًا مفتوح المصدر. هذا هو البيان حتى الآن.',
    aboutTitle: 'من نحن',
    aboutDesc: 'طوني خيروز، مؤسس بلو يولك: مدير فني ومخرج ومنتج أفلام يعمل في المنطقة العربية وأوروبا.',
    contactTitle: 'تواصل',
    contactDesc: 'اكتب إلى بلو يولك بشأن التعاون والإنتاج المشترك واستشارات النصوص.',
    contactLead: 'اكتب إلينا.',
    contactBody: 'منفتحون على التعاون في المشاريع، ومحادثات الإنتاج المشترك، واستشارات النصوص.',
    contactEz: 'الحملات وأعمال العلامات',
    standin: 'نموذج مؤقت',
    standinNote: 'محتوى مؤقت: يُستبدل بعمل حقيقي.',
    notFoundTitle: 'غير موجود',
    notFoundBody: 'هذه الغرفة غير موجودة بعد.',
    notFoundLink: 'العودة إلى المدخل',
    footerLine: 'مختبر إنتاج',
    rights: 'جميع الحقوق محفوظة.',
    readMore: 'افتح',
    landHint: 'أهلًا بك. المس الصفار وحرّكه.',
    landLabel: 'المس الصفار وحرّكه لاختيار صفحة',
    museumTitle: 'متحف لما صنعناه.',
    museumCount: (n) => `${n} معروضًا · المس الصفار`,
    museumHint: 'اسحب للتنقل · المس إطارًا للدخول',
    viewMap: 'الخريطة', viewIndex: 'الفهرس', zoomIn: 'تكبير', zoomOut: 'تصغير',
    open: 'افتح', edgeOfMap: 'حافة الخريطة',
    indexTitle: 'الفهرس', allWorkLabel: 'كل الأعمال',
    exhibitsN: (n) => `${n} معروضًا`,
    allYears: 'كل السنوات', byYear: 'السنة', byCategory: 'الفئة',
    nothingHere: 'لا شيء هنا بعد. جرّب سنة أو فئة أخرى.',
    stills: 'لقطات', watch: 'شاهد الفيلم', frame: 'لقطة', backProject: 'العودة إلى المشروع', backIndex: 'الفهرس',
    stillsTitle: (n) => `${n}: لقطات`, stillsDesc: (n) => `لقطات مختارة من ${n}.`,
    frameOf: (a, b) => `${a} / ${b}`,
    catDesc: (c) => `${c} من مختبر بلو يولك.`,
    labLead: 'الأزرق هو الحبر. الصفار هو الحياة. معًا يصنعان شيئًا جديدًا.',
    meetFounder: 'تعرّف إلى المؤسس', writeUs: 'اكتب إلينا',
    offers: ['تعاون', 'إنتاج مشترك', 'استشارات نصوص'],
    copyMail: 'انسخ العنوان', copied: 'تم النسخ',
    readEntry: 'اقرأ',
    startingFilm: 'جارٍ تشغيل الفيلم', nowPlaying: 'يُعرض الآن',
    minutes: (n) => `${n} دقيقة`,
  },
};
